# Sandbox
For playing around during development.

In [1]:
%pylab inline
#import pysd
#print pysd.__version__
#print pysd.__file__
#import pandas as pd
#import os
import xarray as xr

Populating the interactive namespace from numpy and matplotlib


/Users/houghton/anaconda/lib/python2.7/site-packages/pandas/computation/__init__.py:19: UserWarning: The installed version of numexpr 2.4.4 is not supported in pandas and will be not be used

  UserWarning)


In [2]:
order = 4
a = xr.DataArray(data=[0]*order,
                 coords={'_delay': range(order)})
a

<xarray.DataArray (_delay: 4)>
array([0, 0, 0, 0])
Coordinates:
  * _delay   (_delay) int64 0 1 2 3

In [8]:
# adding a delay to a single variable is straightforward
delay = 8
inval = 1

order = 4
a = xr.DataArray(data=[0]*order,
                 coords={'_delay': range(order)})

ddt = (a/(delay/order)).shift(**{'_delay': 1}).fillna(inval) - (a/(delay/order))
ddt

<xarray.DataArray (_delay: 4)>
array([ 1.,  0.,  0.,  0.])
Coordinates:
  * _delay   (_delay) int64 0 1 2 3

In [18]:
inval = xr.DataArray(data=[1,2,3], coords={'Dim1':['A','B','C']})
print inval

order = 4
a = xr.DataArray(data=np.tile(0, [len(inval), order]),
                 coords={'Dim1':['A','B','C'], '_delay': range(order)})
print a

delay = 8
ddt = (a/(delay/order)).shift(**{'_delay': 1}).fillna(inval) - (a/(delay/order))
ddt

<xarray.DataArray (Dim1: 3)>
array([1, 2, 3])
Coordinates:
  * Dim1     (Dim1) |S1 'A' 'B' 'C'
<xarray.DataArray (Dim1: 3, _delay: 4)>
array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])
Coordinates:
  * Dim1     (Dim1) |S1 'A' 'B' 'C'
  * _delay   (_delay) int64 0 1 2 3


<xarray.DataArray (Dim1: 3, _delay: 4)>
array([[ 1.,  0.,  0.,  0.],
       [ 2.,  0.,  0.,  0.],
       [ 3.,  0.,  0.,  0.]])
Coordinates:
  * Dim1     (Dim1) |S1 'A' 'B' 'C'
  * _delay   (_delay) int64 0 1 2 3

In [20]:
delay = 8
inval = xr.DataArray(data=[1,2,3], coords={'Dim1':['A','B','C']})
print inval

order = 4
a = xr.DataArray(data=np.tile(0, [len(inval), order]),
                 coords={'Dim1':['A','B','C'], '_delay': range(order)})
print a

gap = a.shift(**{'_delay': 1}).fillna(inval) - a 
ddt = gap /(delay/order)
ddt

<xarray.DataArray (Dim1: 3)>
array([1, 2, 3])
Coordinates:
  * Dim1     (Dim1) |S1 'A' 'B' 'C'
<xarray.DataArray (Dim1: 3, _delay: 4)>
array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])
Coordinates:
  * Dim1     (Dim1) |S1 'A' 'B' 'C'
  * _delay   (_delay) int64 0 1 2 3


<xarray.DataArray (Dim1: 3, _delay: 4)>
array([[ 0.5,  0. ,  0. ,  0. ],
       [ 1. ,  0. ,  0. ,  0. ],
       [ 1.5,  0. ,  0. ,  0. ]])
Coordinates:
  * Dim1     (Dim1) |S1 'A' 'B' 'C'
  * _delay   (_delay) int64 0 1 2 3

In [21]:
(a.shift(**{'_delay': 1}).fillna(inval) - a )/(delay/order)

<xarray.DataArray (Dim1: 3, _delay: 4)>
array([[ 0.5,  0. ,  0. ,  0. ],
       [ 1. ,  0. ,  0. ,  0. ],
       [ 1.5,  0. ,  0. ,  0. ]])
Coordinates:
  * Dim1     (Dim1) |S1 'A' 'B' 'C'
  * _delay   (_delay) int64 0 1 2 3

In [158]:
for i in range(5):
    outflows = a/(delay/order)
    inflows = outflows.shift(**{'_delay': 1})
    inflows.loc[{'_delay': 0}] = inval
    outval = outflows.loc[{'_delay': order-1}]
    a = a + inflows - outflows
    print a

<xarray.DataArray (_delay: 4)>
array([ 1.,  0.,  0.,  0.])
Coordinates:
  * _delay   (_delay) int64 0 1 2 3
<xarray.DataArray (_delay: 4)>
array([ 1.5,  0.5,  0. ,  0. ])
Coordinates:
  * _delay   (_delay) int64 0 1 2 3
<xarray.DataArray (_delay: 4)>
array([ 1.75,  1.  ,  0.25,  0.  ])
Coordinates:
  * _delay   (_delay) int64 0 1 2 3
<xarray.DataArray (_delay: 4)>
array([ 1.875,  1.375,  0.625,  0.125])
Coordinates:
  * _delay   (_delay) int64 0 1 2 3
<xarray.DataArray (_delay: 4)>
array([ 1.9375,  1.625 ,  1.    ,  0.375 ])
Coordinates:
  * _delay   (_delay) int64 0 1 2 3


In [6]:
(a/(delay/order)).shift(**{'_delay': 1}).fillna(inval) - (a/(delay/order))

<xarray.DataArray (_delay: 4)>
array([ 1.,  0.,  0.,  0.])
Coordinates:
  * _delay   (_delay) int64 0 1 2 3

In [164]:
order = 5.3
try:
    range(order)
except TypeError or ValueError:
    raise TypeError('Order of delay must be an integer, instead recieved %s' % str(order))

TypeError: Order of delay must be an integer, instead recieved 5.3