# Sandbox
For playing around during development.

In [2]:
%pylab inline
import pysd
print pysd.__version__
print pysd.__file__
import pandas as pd

Populating the interactive namespace from numpy and matplotlib
0.3.2
pysd/__init__.py


In [25]:
model = pysd.load('tests/dev_tests/test_subscript_1d_arrays_hand_code.py')
model.run().head()

0       1        2
0.000  0.00000  0.0000  0.00000
0.125  0.00125  0.0025  0.00375
0.250  0.00250  0.0050  0.00750
0.375  0.00375  0.0075  0.01125
0.500  0.00500  0.0100  0.01500

In [5]:
model = pysd.load('tests/dev_tests/test_subscript_1d_arrays_hand_code_scramble.py')
model.run().head()

AttributeError: 'function' object has no attribute 'loc'

In [26]:
model = pysd.load('tests/dev_tests/test_subscript_2d_arrays_hand_code.py')
model.run().head()

0     1     2     3     4     5
0  1.00  2.00  3.00  4.00  5.00  6.00
1  1.01  2.02  3.03  4.04  5.05  6.06
2  1.02  2.04  3.06  4.08  5.10  6.12
3  1.03  2.06  3.09  4.12  5.15  6.18
4  1.04  2.08  3.12  4.16  5.20  6.24

In [12]:
import numpy as np
a=np.array([1,2,3])
dim_dict={"entry1":0,"entry2":1,"entry3":2}
%timeit [a[dim_dict["entry2"]],a[dim_dict["entry1"]],a[dim_dict["entry2"]]]

The slowest run took 11.03 times longer than the fastest. This could mean that an intermediate result is being cached 
1000000 loops, best of 3: 367 ns per loop


In [19]:
import numpy as np
a=np.array([1,2,3])
dim_dict={"entry1":0,"entry2":1,"entry3":2}
%timeit np.array([a[dim_dict["entry2"]],a[dim_dict["entry1"]]3,a[dim_dict["entry2"]]])

SyntaxError: invalid syntax (<unknown>, line 1)

In [14]:
import numpy as np
a=np.array([1,2,3])
dim_dict={"entry1":0,"entry2":1,"entry3":2}
%timeit a[[dim_dict["entry2"],dim_dict["entry1"],dim_dict["entry2"]]]

The slowest run took 9.35 times longer than the fastest. This could mean that an intermediate result is being cached 
1000000 loops, best of 3: 1.3 µs per loop


In [18]:
np.array([1,2,3,5]) * [2,3,4,5]

array([ 2,  6, 12, 25])

In [9]:
dim_dict = {'One Dimensional Subscript': ['Entry 1', 'Entry 2', 'Entry 3']}
rate_a = DataArray([.01,.02,.03], dim_dict)
%timeit rate_a.loc[['Entry 2', 'Entry 1', 'Entry 3']]

1000 loops, best of 3: 275 µs per loop


In [ ]:
dim_dict = {'One Dimensional Subscript': ['Entry 1', 'Entry 2', 'Entry 3']}
rate_a = DataArray([.01,.02,.03], dim_dict)
%timeit rate_a.loc[['Entry 2', 'Entry 1', 'Entry 3']]

In [48]:
model = pysd.load('tests/dev_tests/test_subscript_aggregation_hand_code.py')
print model.components.sub1d_sum()
print model.components.sub_secondary_sum()
model.run()
print model.components.sub1d_sum()
#model.
#model.run(return_columns=['stock_a', 'sub1d_sum', 'sub_secondary_sum']).head()
#model.run(return_columns=['sub1d_sum']).head()

RuntimeError: maximum recursion depth exceeded in cmp

In [21]:
dim_dict={}
dim_dict['Column Subscripts'] = slice()
dim_dict['Row Subscripts'] = ['Entry 1', 'Entry 2', 'Entry 3']

In [25]:
dim_dict={}
dim_dict["Column 1"]=0
dim_dict["Column 2"]=1
dim_dict["Entry 1"]=0
dim_dict["Entry 2"]=1
dim_dict["Entry 3"]=2
dim_dict


In [34]:

dim_dict = {'Second_D': ['Column_1', 'Column_2'], 
            'One_D': ['Entry_1', 'Entry_2', 'Entry_3']}

#dim_dict = {'suba': ['subb1', 'subb2'],
#            'subb': ['suba1', 'suba2', 'suba3']}

a = DataArray([[1,2],[3,4],[5,6]], dim_dict)
a.sum('One_D')

<xray.DataArray (Second_D: 2)>
array([ 9, 12])
Coordinates:
  * Second_D  (Second_D) |S8 'Column_1' 'Column_2'

<xray.DataArray (One_D: 3)>
array([ 3,  7, 11])
Coordinates:
  * One_D    (One_D) |S7 'Entry_1' 'Entry_2' 'Entry_3'

In [4]:
%debug

> /Users/houghton/anaconda/lib/python2.7/site-packages/xray/core/indexing.py(35)expanded_indexer()
     34     if len(new_key) > ndim:
---> 35         raise IndexError('too many indices')
     36     new_key.extend((ndim - len(new_key)) * [slice(None)])

ipdb> u
> /Users/houghton/anaconda/lib/python2.7/site-packages/xray/core/dataarray.py(79)_remap_key()
     78             # expand the indexer so we can handle Ellipsis
---> 79             key = indexing.expanded_indexer(key, self.data_array.ndim)
     80             return tuple(lookup_positions(dim, labels) for dim, labels

ipdb> u
> /Users/houghton/anaconda/lib/python2.7/site-packages/xray/core/dataarray.py(84)__getitem__()
     83     def __getitem__(self, key):
---> 84         return self.data_array[self._remap_key(key)]
     85 

ipdb> u
> /Users/houghton/Google_Drive/Academic Projects/PYSD/pysd/pysd/builder/componentClass.py(112)set_state()
    111                 size = self.state[key].size
--> 112                 self.state[ke

In [6]:
model = pysd.load('tests/Teacup_sub_test1.py')
model.run().head()

0        1        2      3       4      5
0.000  180.000  160.000  100.000  10.00  1.0000  190.0
0.125  178.625  158.875   99.625  10.75  1.8625  188.5
0.250  177.250  157.750   99.250  11.50  2.7250  187.0
0.375  175.875  156.625   98.875  12.25  3.5875  185.5
0.500  174.500  155.500   98.500  13.00  4.4500  184.0

In [11]:
np.array([5,3,4]).reshape((3))

array([5, 3, 4])

In [6]:
a = DataArray([5,3,4])[0:3]

In [7]:
a.values=[4,5,6]

In [1]:
from xray import DataArray

In [14]:
dim_dict = {'suba': ['subb1', 'subb2'],
            'subb': ['suba1', 'suba2', 'suba3']}
DataArray([[50, 60, 70]], {'subb':dim_dict['subb']})

ValueError: coordinate subb has dimensions ('subb',), but these are not a subset of the DataArray dimensions ['dim_0', 'dim_1']

In [ ]:
dim_dict.

In [6]:
model.components.get_state()

[180, 160, 100, 10, 1, 190]

In [ ]:
model.components.

# Testing various subscript Options


In [12]:
from __future__ import division 
import numpy as np 
from pysd import functions
from scipy.integrate import odeint
import itertools

### option 1: unnamed array

In [13]:
class MinModel(object):
    ##########  boilerplate stuff from the existing pysd #########
    def __init__(self):
        self._stocknames = [name[:-5] for name in dir(self) if name[-5:] == '_init']
        self._stocknames.sort() #inplace
        self._dfuncs = [getattr(self, 'd%s_dt'%name) for name in self._stocknames]
        self.state = dict(zip(self._stocknames, [None]*len(self._stocknames)))
        self.reset_state()
        self.functions = functions.Functions(self)

    def reset_state(self):
        """Sets the model state to the state described in the model file. """
        self.t = self.initial_time() #set the initial time
        retry_flag = False
        for key in self.state.keys():
            try:
                self.state[key] = eval('self.'+key+'_init()') #set the initial state
            except TypeError:
                retry_flag = True
        if retry_flag:
            self.reset_state() #potential for infinite loop!

    ########### Stuff we have to modify to make subscripts work #########
    def d_dt(self, state_vector, t):
        """The primary purpose of this function is to interact with the integrator.
        It takes a state vector, sets the state of the system based on that vector,
        and returns a derivative of the state vector
        """        
        self.set_state(state_vector)
        self.t = t
        
        derivative_vector = []
        for func in self._dfuncs:
            derivative_vector += list(func())
            
        return derivative_vector

    def set_state(self, state_vector):
        i = 0
        for key in self._stocknames:
            if isinstance(self.state[key], np.ndarray):
                size = self.state[key].size
                elements = state_vector[i:i+size]
                shape = self.state[key].shape
                self.state[key] = np.array(elements).reshape(shape)
                i += size
            else:
                self.state[key] = state_vector[i]
                i += 1

        
    def get_state(self):
        #if we keep this, we should make it fully a list comprehension
        state_vector = []
        for item in [self.state[key] for key in self._stocknames]:
            if isinstance(item, np.ndarray):
                state_vector += list(item.flatten())
            else:
                state_vector += list(item)
        return state_vector
    
    
    ######### model specific components (that go in the model file)
    suba_list = ['suba1', 'suba2', 'suba3']
    subb_list = ['suba2', 'subb2']
    suba_index = dict(zip(suba_list, range(len(suba_list))))
    subb_index = dict(zip(subb_list, range(len(subb_list))))
    
    def stock(self, suba, subb):
        return self.state['stock'][self.suba_index[suba]][self.subb_index[subb]] 
    
    def stock_init(self):
        return np.array([[1,1],[1,1],[1,1]])
    
    def dstock_dt(self):
        return [self.flow(suba, subb) for suba, subb in itertools.product(self.suba_list, self.subb_list)]
    
    def constant(self, suba, subb):
        return self.constant.values[self.suba_index[suba]][self.subb_index[subb]]
    constant.values = np.array([[1,2],[3,4],[5,6]])
    
    def flow(self, suba, subb):
        return self.constant(suba, subb) * self.stock(suba, subb)
    
    def initial_time(self):
        return 0

In [14]:
a = MinModel()

In [15]:
%%timeit
a.reset_state()
odeint(a.d_dt, a.get_state(), range(10))

100 loops, best of 3: 16.6 ms per loop


In [34]:
%%prun
odeint(a.d_dt, a.get_state(), range(10))

### option 2: xray's `DataArray`

In [19]:
from xray import DataArray

class xMinModel(object):
    ##########  boilerplate stuff from the existing pysd #########
    def __init__(self):
        self._stocknames = [name[:-5] for name in dir(self) if name[-5:] == '_init']
        self._stocknames.sort() #inplace
        self._dfuncs = [getattr(self, 'd%s_dt'%name) for name in self._stocknames]
        self.state = dict(zip(self._stocknames, [None]*len(self._stocknames)))
        self.reset_state()
        self.functions = functions.Functions(self)

    def reset_state(self):
        """Sets the model state to the state described in the model file. """
        self.t = self.initial_time() #set the initial time
        retry_flag = False
        for key in self.state.keys():
            try:
                self.state[key] = eval('self.'+key+'_init()') #set the initial state
            except TypeError:
                retry_flag = True
        if retry_flag:
            self.reset_state() #potential for infinite loop!

    ########### Stuff we have to modify to make subscripts work #########
    def d_dt(self, state_vector, t):
        """The primary purpose of this function is to interact with the integrator.
        It takes a state vector, sets the state of the system based on that vector,
        and returns a derivative of the state vector
        """        
        self.set_state(state_vector)
        self.t = t
        
        derivative_vector = []
        for func in self._dfuncs:
            derivative_vector += list(func())
            
        return derivative_vector

    def set_state(self, state_vector):
        i = 0
        for key in self._stocknames:
            if isinstance(self.state[key], DataArray):
                shape = self.state[key].shape
                size = self.state[key].size
                self.state[key].loc[:,:] = np.array(state_vector[i:i+size]).reshape(shape)
                i += size
            else:
                self.state[key] = state_vector[i]
                i += 1
        
    def get_state(self):
        #if we keep this, we should make it fully a list comprehension
        state_vector = []
        for item in [self.state[key] for key in self._stocknames]:
            if isinstance(item, DataArray):
                state_vector += list(item.values.flatten())
            else:
                state_vector += list(item)
        return state_vector
    
    
    ######### model specific components (that go in the model file)
    dim_dict = {'suba': ['subb1', 'subb2'],
                'subb': ['suba1', 'suba2', 'suba3']}
    
    def stock(self, suba, subb):
        return self.state['stock'].loc[suba, subb].values
    
    def stock_init(self):
        return DataArray([[1,1],[1,1],[1,1]], self.dim_dict)
    
    def dstock_dt(self):
        return [self.flow(suba, subb) for suba, subb in itertools.product(*self.dim_dict.values())]
    
    def constant(self, suba, subb):
        #values = DataArray([[1,2],[3,4],[5,6]], self.dim_dict)
        return self.constant.values.loc[suba, subb].values
    constant.values = DataArray([[1,2],[3,4],[5,6]], dim_dict)
    
    def flow(self, suba, subb):
        return self.constant(suba, subb) * self.stock(suba, subb)
    
    def initial_time(self):
        return 0

In [20]:
a = cMinModel()

In [18]:
%%timeit
a.reset_state()
odeint(a.d_dt, a.get_state(), range(10))

100 loops, best of 3: 16.6 ms per loop


In [26]:
%%prun
odeint(a.d_dt, a.get_state(), range(10))

Excess work done on this call (perhaps wrong Dfun type).
Run with full_output = 1 to get quantitative information.
 

# Option 3

Instead of calling the functions each time for each value of the subscript, can we call a function once, and get all of the values? Then we're doing array mathematics instead of a bunch of one-off multiplication.

This is nice, and faster, but i'm not sure how we would scale it to deal with elements with different functions.

In [38]:
class fMinModel(object):
    ##########  boilerplate stuff from the existing pysd #########
    def __init__(self):
        self._stocknames = [name[:-5] for name in dir(self) if name[-5:] == '_init']
        self._stocknames.sort() #inplace
        self._dfuncs = [getattr(self, 'd%s_dt'%name) for name in self._stocknames]
        self.state = dict(zip(self._stocknames, [None]*len(self._stocknames)))
        self.reset_state()
        self.functions = functions.Functions(self)

    def reset_state(self):
        """Sets the model state to the state described in the model file. """
        self.t = self.initial_time() #set the initial time
        retry_flag = False
        for key in self.state.keys():
            try:
                self.state[key] = eval('self.'+key+'_init()') #set the initial state
            except TypeError:
                retry_flag = True
        if retry_flag:
            self.reset_state() #potential for infinite loop!

    ########### Stuff we have to modify to make subscripts work #########
    def d_dt(self, state_vector, t):
        """The primary purpose of this function is to interact with the integrator.
        It takes a state vector, sets the state of the system based on that vector,
        and returns a derivative of the state vector
        """        
        self.set_state(state_vector)
        self.t = t
        
        derivative_vector = []
        for func in self._dfuncs:
            res = func()
            if isinstance(res, np.ndarray):
                res = res.flatten()
            derivative_vector += list(res)
            
        return derivative_vector

    def set_state(self, state_vector):
        i = 0
        for key in self._stocknames:
            
            if isinstance(self.state[key], np.ndarray):
                size = self.state[key].size
                elements = state_vector[i:i+size]
                shape = self.state[key].shape
                self.state[key] = np.array(elements).reshape(shape)
                i += size
            else:
                self.state[key] = state_vector[i]
                i += 1

        
    def get_state(self):
        #if we keep this, we should make it fully a list comprehension
        state_vector = []
        for item in [self.state[key] for key in self._stocknames]:
            if isinstance(item, np.ndarray):
                state_vector += list(item.flatten())
            else:
                state_vector += list(item)
        return state_vector
    
    
    ######### model specific components (that go in the model file)
    
    def stock(self):
        return self.state['stock']
    
    def stock_init(self):
        return np.array([[1,1],[1,1],[1,1]])
    
    def dstock_dt(self):
        return self.flow()
    
    def constant(self):
        return np.array([[1,2],[3,4],[5,6]])
    
    def constant2(self):
        return 6
    
    def flow(self):
        return self.constant() * self.stock()
    
    def initial_time(self):
        return 0

In [39]:
a = fMinModel()

In [37]:
%%timeit
a.reset_state()
odeint(a.d_dt, a.get_state(), range(10))

100 loops, best of 3: 9.09 ms per loop
